version: '3.3'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    port:
      - 27017:27017
    command:
      - mongod
    volumes:
      - ./tmp/db:/data/db

  frontend:
    image: nazrin
    build: .
    links:
      - mongodb
    restart: always
    environment:
      NODE_ENV: production
      MONGO_DATABASE=mongodb://mongodb/nazri
      PORT: 3000
      WAIT_HOSTS: db:27017
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app/api
      - ./client:/usr/src/app/client
